### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by potmo** [schwa/Compute#8]
In some of the examples you just run (eg. [here](https://github.com/schwa/Compute/blob/41634bc9808559ca696308ca231eb86b3853de64/Sources/Examples/Examples/HelloWorldDemo.swift#L24))

```
compute.run(...)
```
and in some you do all the steps manually (eg. [here](https://github.com/schwa/Compute/blob/41634bc9808559ca696308ca231eb86b3853de64/Sources/Examples/Examples/GameOfLife/GameOfLife.swift#L80))

```
try compute.task { task in
   try task { dispatch in
      try dispatch(....)
   }
}
```

Is there any reason to prefer the second version before the first?

**Comment by schwa** [comment]
They're both equivalent. `run` is just more convenient at the expensive of less flexibility.. 

```
compute.run(A)
compute.run(B)
compute.run(C)
```

```
compute.task { task in
  task { dispatch in
    dispatch(A)
    dispatch(B)
    dispatch(C)
  }
}
```

The first example will wait for the first shader to complete before running the second shader… and so on.
The second example submits them all to Metal in the same pass and allows metal to optimise if needed. It only waits for completion once.

I am thinking of deprecating `run` possibly.

**Comment by potmo** [comment]
Thanks. I see... so if I want to pass a texture for example through multiple shaders without hitting the CPU in between I would use the second one. I think the variant of run that is used in the example in the readme is actually deprecated.
